name: .NET Core CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: server/

    - name: Build
      run: dotnet build --no-restore
      working-directory: server/

    - name: Execute unit tests
      run: dotnet test --no-build --verbosity normal
      working-directory: server/
